name: yelpax
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  flutter_smart_dialog: ^4.9.8+8
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  logger: ^2.6.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  dartz: ^0.10.1
  sqflite: ^2.4.2
  path: ^1.9.1
  video_player: ^2.10.0
  chewie: ^1.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/y_logo.png"
  android: true
  ios: true



  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/images/splash_1.jpg


  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
        - asset: assets/fonts/Inter_Bold.ttf
        - asset: assets/fonts/Inter_Italic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

